### ISSUE TITLE
[Feature request] Additional controls to interactively change overly offset and size

### ISSUE THREAD

**Issue by laheller** [AllskyTeam/allsky-website#148]
Hi @EricClaeys  !

As the [documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/AllskyTeam/allsky/master/html/documentation/explanations/constellationOverlay.html) about constellation overlay says, it is very hard & time consuming to properly align the constellation overlay with the real star map coming from the camera. It's kind of annoying to play with the _configuration.json_ entries and then refresh the website to check the results.
The idea is to add some additional controls, like buttons for example to a new bottom panel which appears only when the constellations overlay is enabled. The following buttons could be connected to and change the value of settings interactively:

- a pair of buttons with label `Size -` and `Size +` to decrease/increase the overlay size (while keeping the aspect ratio) => **overlayWidth** & **overlayHeight** in the _configuration.json_
- a pair of buttons with label `Offset X-` and `Offset X+` to change the horizontal offset of the overlay => **overlayOffsetLeft** in the _configuration.json_
- a pair of buttons with label `Offset Y-` and `Offset Y+` to change the vertical offset of the overlay => **overlayOffsetTop** in the _configuration.json_

**Comment by EricClaeys** [comment]
@laheller, thanks for the suggestion.  I added your idea to the [existing enhancement request](https://github.com/AllskyTeam/allsky/issues/2923) for improving how the constellation overlay is changed.
So, I'm closing this Issue.  Please post any follow-up to the other Issue.
